/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2016.  Dmytro Karataiev
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package com.adkdevelopment.yalantisinternship.remote;

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;

/**
 * Autogenerated class of RSSNewsItems from the "TASKS" API
 * Implements Parcelable to be as fast as possible in transmission between activities
 */
public class RSSNewsItem implements Parcelable {

    public static final String TASKITEM = "task";

    @SerializedName("id")
    @Expose
    private String id;
    @SerializedName("photo")
    @Expose
    private List<String> photo = new ArrayList<>();
    @SerializedName("title")
    @Expose
    private String title;
    @SerializedName("owner")
    @Expose
    private String owner;
    @SerializedName("status")
    @Expose
    private String status;
    @SerializedName("created")
    @Expose
    private String created;
    @SerializedName("registered")
    @Expose
    private String registered;
    @SerializedName("assigned")
    @Expose
    private String assigned;
    @SerializedName("responsible")
    @Expose
    private String responsible;
    @SerializedName("description")
    @Expose
    private String description;

    /**
     *
     * @return
     * The id
     */
    public String getId() {
        return id;
    }

    /**
     *
     * @param id
     * The id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     *
     * @return
     * The photo
     */
    public List<String> getPhoto() {
        return photo;
    }

    /**
     *
     * @param photo
     * The photo
     */
    public void setPhoto(List<String> photo) {
        this.photo = photo;
    }

    /**
     *
     * @return
     * The title
     */
    public String getTitle() {
        return title;
    }

    /**
     *
     * @param title
     * The title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     *
     * @return
     * The owner
     */
    public String getOwner() {
        return owner;
    }

    /**
     *
     * @param owner
     * The owner
     */
    public void setOwner(String owner) {
        this.owner = owner;
    }

    /**
     *
     * @return
     * The status
     */
    public String getStatus() {
        return status;
    }

    /**
     *
     * @param status
     * The status
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     *
     * @return
     * The created
     */
    public String getCreated() {
        return created;
    }

    /**
     *
     * @param created
     * The created
     */
    public void setCreated(String created) {
        this.created = created;
    }

    /**
     *
     * @return
     * The registered
     */
    public String getRegistered() {
        return registered;
    }

    /**
     *
     * @param registered
     * The registered
     */
    public void setRegistered(String registered) {
        this.registered = registered;
    }

    /**
     *
     * @return
     * The assigned
     */
    public String getAssigned() {
        return assigned;
    }

    /**
     *
     * @param assigned
     * The assigned
     */
    public void setAssigned(String assigned) {
        this.assigned = assigned;
    }

    /**
     *
     * @return
     * The responsible
     */
    public String getResponsible() {
        return responsible;
    }

    /**
     *
     * @param responsible
     * The responsible
     */
    public void setResponsible(String responsible) {
        this.responsible = responsible;
    }

    /**
     *
     * @return
     * The description
     */
    public String getDescription() {
        return description;
    }

    /**
     *
     * @param description
     * The description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.id);
        dest.writeStringList(this.photo);
        dest.writeString(this.title);
        dest.writeString(this.owner);
        dest.writeString(this.status);
        dest.writeString(this.created);
        dest.writeString(this.registered);
        dest.writeString(this.assigned);
        dest.writeString(this.responsible);
        dest.writeString(this.description);
    }

    public RSSNewsItem() {
    }

    private RSSNewsItem(Parcel in) {
        this.id = in.readString();
        this.photo = in.createStringArrayList();
        this.title = in.readString();
        this.owner = in.readString();
        this.status = in.readString();
        this.created = in.readString();
        this.registered = in.readString();
        this.assigned = in.readString();
        this.responsible = in.readString();
        this.description = in.readString();
    }

    public static final Creator<RSSNewsItem> CREATOR = new Creator<RSSNewsItem>() {
        public RSSNewsItem createFromParcel(Parcel source) {
            return new RSSNewsItem(source);
        }

        public RSSNewsItem[] newArray(int size) {
            return new RSSNewsItem[size];
        }
    };
}